#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUN_TESTS=1
RUN_APP=0

for arg in "$@"; do
  case "$arg" in
    --skip-tests)
      RUN_TESTS=0
      ;;
    --run)
      RUN_APP=1
      ;;
    -h|--help)
      cat <<'EOF'
Usage: scripts/rebuild-install.sh [--skip-tests] [--run]

Rebuild WT Clipper from a clean source checkout state and install the Linux
desktop package generated by Tauri.

Options:
  --skip-tests  Skip cargo test before building the app package.
  --run         Start the installed app after installation.
EOF
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

echo "[1/6] Installing frontend dependencies if needed..."
if [[ ! -d frontend/node_modules ]]; then
  npm --prefix frontend install
else
  npm --prefix frontend install
fi

if [[ "$RUN_TESTS" -eq 1 ]]; then
  echo "[2/6] Running Rust tests..."
  cargo test
else
  echo "[2/6] Skipping Rust tests."
fi

echo "[3/6] Building frontend..."
npm run frontend:build

echo "[4/6] Building Tauri package..."
npm run build

echo "[5/6] Locating generated Linux package..."
DEB_PACKAGE="$(find src-tauri/target/release/bundle/deb -maxdepth 1 -type f -name '*.deb' 2>/dev/null | sort | tail -n 1 || true)"
RPM_PACKAGE="$(find src-tauri/target/release/bundle/rpm -maxdepth 1 -type f -name '*.rpm' 2>/dev/null | sort | tail -n 1 || true)"

echo "[6/6] Installing package..."
if command -v dpkg >/dev/null 2>&1 && [[ -n "$DEB_PACKAGE" ]]; then
  echo "Installing $DEB_PACKAGE"
  sudo dpkg -i "$DEB_PACKAGE" || sudo apt-get install -f -y
elif command -v rpm >/dev/null 2>&1 && [[ -n "$RPM_PACKAGE" ]]; then
  echo "Installing $RPM_PACKAGE"
  if command -v dnf >/dev/null 2>&1; then
    sudo dnf install -y "$RPM_PACKAGE"
  elif command -v zypper >/dev/null 2>&1; then
    sudo zypper --non-interactive install --allow-unsigned-rpm "$RPM_PACKAGE"
  else
    sudo rpm -Uvh --replacepkgs "$RPM_PACKAGE"
  fi
else
  echo "No installable package found for this system." >&2
  echo "Looked for:" >&2
  echo "  src-tauri/target/release/bundle/deb/*.deb" >&2
  echo "  src-tauri/target/release/bundle/rpm/*.rpm" >&2
  exit 1
fi

echo "WT Clipper rebuilt and installed."

if [[ "$RUN_APP" -eq 1 ]]; then
  if command -v wt-clipper-tauri >/dev/null 2>&1; then
    wt-clipper-tauri >/dev/null 2>&1 &
  elif command -v gtk-launch >/dev/null 2>&1; then
    gtk-launch "WT Clipper" >/dev/null 2>&1 &
  else
    echo "Installed. Start WT Clipper from your application menu."
  fi
fi
